// Code generated by cmd/gen-unimplemented. DO NOT EDIT.

package api

import (
	"context"

	gen "github.com/saeedafri/sms-be/internal/gen/api"
)

// Unimplemented answers 501 for every contract operation.
// Server embeds it; each stage shadows the operations it implements.
type Unimplemented struct{}

func (Unimplemented) GetAlerts(ctx context.Context, request gen.GetAlertsRequestObject) (gen.GetAlertsResponseObject, error) {
	return nil, errNotImplemented("GetAlerts")
}

func (Unimplemented) UpdateAlerts(ctx context.Context, request gen.UpdateAlertsRequestObject) (gen.UpdateAlertsResponseObject, error) {
	return nil, errNotImplemented("UpdateAlerts")
}

func (Unimplemented) UpdateScheduledReport(ctx context.Context, request gen.UpdateScheduledReportRequestObject) (gen.UpdateScheduledReportResponseObject, error) {
	return nil, errNotImplemented("UpdateScheduledReport")
}

func (Unimplemented) Login(ctx context.Context, request gen.LoginRequestObject) (gen.LoginResponseObject, error) {
	return nil, errNotImplemented("Login")
}

func (Unimplemented) Logout(ctx context.Context, request gen.LogoutRequestObject) (gen.LogoutResponseObject, error) {
	return nil, errNotImplemented("Logout")
}

func (Unimplemented) VerifyMfaChallenge(ctx context.Context, request gen.VerifyMfaChallengeRequestObject) (gen.VerifyMfaChallengeResponseObject, error) {
	return nil, errNotImplemented("VerifyMfaChallenge")
}

func (Unimplemented) DisableMfa(ctx context.Context, request gen.DisableMfaRequestObject) (gen.DisableMfaResponseObject, error) {
	return nil, errNotImplemented("DisableMfa")
}

func (Unimplemented) EnrollMfa(ctx context.Context, request gen.EnrollMfaRequestObject) (gen.EnrollMfaResponseObject, error) {
	return nil, errNotImplemented("EnrollMfa")
}

func (Unimplemented) ConfirmMfaEnrollment(ctx context.Context, request gen.ConfirmMfaEnrollmentRequestObject) (gen.ConfirmMfaEnrollmentResponseObject, error) {
	return nil, errNotImplemented("ConfirmMfaEnrollment")
}

func (Unimplemented) ChangePassword(ctx context.Context, request gen.ChangePasswordRequestObject) (gen.ChangePasswordResponseObject, error) {
	return nil, errNotImplemented("ChangePassword")
}

func (Unimplemented) RequestPasswordReset(ctx context.Context, request gen.RequestPasswordResetRequestObject) (gen.RequestPasswordResetResponseObject, error) {
	return nil, errNotImplemented("RequestPasswordReset")
}

func (Unimplemented) ResetPassword(ctx context.Context, request gen.ResetPasswordRequestObject) (gen.ResetPasswordResponseObject, error) {
	return nil, errNotImplemented("ResetPassword")
}

func (Unimplemented) Signup(ctx context.Context, request gen.SignupRequestObject) (gen.SignupResponseObject, error) {
	return nil, errNotImplemented("Signup")
}

func (Unimplemented) ConfirmVerificationEmail(ctx context.Context, request gen.ConfirmVerificationEmailRequestObject) (gen.ConfirmVerificationEmailResponseObject, error) {
	return nil, errNotImplemented("ConfirmVerificationEmail")
}

func (Unimplemented) ResendVerificationEmail(ctx context.Context, request gen.ResendVerificationEmailRequestObject) (gen.ResendVerificationEmailResponseObject, error) {
	return nil, errNotImplemented("ResendVerificationEmail")
}

func (Unimplemented) ListJourneys(ctx context.Context, request gen.ListJourneysRequestObject) (gen.ListJourneysResponseObject, error) {
	return nil, errNotImplemented("ListJourneys")
}

func (Unimplemented) CreateJourney(ctx context.Context, request gen.CreateJourneyRequestObject) (gen.CreateJourneyResponseObject, error) {
	return nil, errNotImplemented("CreateJourney")
}

func (Unimplemented) GetJourney(ctx context.Context, request gen.GetJourneyRequestObject) (gen.GetJourneyResponseObject, error) {
	return nil, errNotImplemented("GetJourney")
}

func (Unimplemented) UpdateJourney(ctx context.Context, request gen.UpdateJourneyRequestObject) (gen.UpdateJourneyResponseObject, error) {
	return nil, errNotImplemented("UpdateJourney")
}

func (Unimplemented) ActivateJourney(ctx context.Context, request gen.ActivateJourneyRequestObject) (gen.ActivateJourneyResponseObject, error) {
	return nil, errNotImplemented("ActivateJourney")
}

func (Unimplemented) ArchiveJourney(ctx context.Context, request gen.ArchiveJourneyRequestObject) (gen.ArchiveJourneyResponseObject, error) {
	return nil, errNotImplemented("ArchiveJourney")
}

func (Unimplemented) PauseJourney(ctx context.Context, request gen.PauseJourneyRequestObject) (gen.PauseJourneyResponseObject, error) {
	return nil, errNotImplemented("PauseJourney")
}

func (Unimplemented) ResumeJourney(ctx context.Context, request gen.ResumeJourneyRequestObject) (gen.ResumeJourneyResponseObject, error) {
	return nil, errNotImplemented("ResumeJourney")
}

func (Unimplemented) EstimateCost(ctx context.Context, request gen.EstimateCostRequestObject) (gen.EstimateCostResponseObject, error) {
	return nil, errNotImplemented("EstimateCost")
}

func (Unimplemented) ListInvoices(ctx context.Context, request gen.ListInvoicesRequestObject) (gen.ListInvoicesResponseObject, error) {
	return nil, errNotImplemented("ListInvoices")
}

func (Unimplemented) GetInvoice(ctx context.Context, request gen.GetInvoiceRequestObject) (gen.GetInvoiceResponseObject, error) {
	return nil, errNotImplemented("GetInvoice")
}

func (Unimplemented) GetUsage(ctx context.Context, request gen.GetUsageRequestObject) (gen.GetUsageResponseObject, error) {
	return nil, errNotImplemented("GetUsage")
}

func (Unimplemented) ListContactLists(ctx context.Context, request gen.ListContactListsRequestObject) (gen.ListContactListsResponseObject, error) {
	return nil, errNotImplemented("ListContactLists")
}

func (Unimplemented) CreateContactList(ctx context.Context, request gen.CreateContactListRequestObject) (gen.CreateContactListResponseObject, error) {
	return nil, errNotImplemented("CreateContactList")
}

func (Unimplemented) DeleteContactList(ctx context.Context, request gen.DeleteContactListRequestObject) (gen.DeleteContactListResponseObject, error) {
	return nil, errNotImplemented("DeleteContactList")
}

func (Unimplemented) GetContactList(ctx context.Context, request gen.GetContactListRequestObject) (gen.GetContactListResponseObject, error) {
	return nil, errNotImplemented("GetContactList")
}

func (Unimplemented) RenameContactList(ctx context.Context, request gen.RenameContactListRequestObject) (gen.RenameContactListResponseObject, error) {
	return nil, errNotImplemented("RenameContactList")
}

func (Unimplemented) RemoveContactListMember(ctx context.Context, request gen.RemoveContactListMemberRequestObject) (gen.RemoveContactListMemberResponseObject, error) {
	return nil, errNotImplemented("RemoveContactListMember")
}

func (Unimplemented) ListContacts(ctx context.Context, request gen.ListContactsRequestObject) (gen.ListContactsResponseObject, error) {
	return nil, errNotImplemented("ListContacts")
}

func (Unimplemented) ImportContacts(ctx context.Context, request gen.ImportContactsRequestObject) (gen.ImportContactsResponseObject, error) {
	return nil, errNotImplemented("ImportContacts")
}

func (Unimplemented) RemoveIpAllowlistEntry(ctx context.Context, request gen.RemoveIpAllowlistEntryRequestObject) (gen.RemoveIpAllowlistEntryResponseObject, error) {
	return nil, errNotImplemented("RemoveIpAllowlistEntry")
}

func (Unimplemented) GetMe(ctx context.Context, request gen.GetMeRequestObject) (gen.GetMeResponseObject, error) {
	return nil, errNotImplemented("GetMe")
}

func (Unimplemented) UpdateMe(ctx context.Context, request gen.UpdateMeRequestObject) (gen.UpdateMeResponseObject, error) {
	return nil, errNotImplemented("UpdateMe")
}

func (Unimplemented) ListMessages(ctx context.Context, request gen.ListMessagesRequestObject) (gen.ListMessagesResponseObject, error) {
	return nil, errNotImplemented("ListMessages")
}

func (Unimplemented) GetAbuseQueue(ctx context.Context, request gen.GetAbuseQueueRequestObject) (gen.GetAbuseQueueResponseObject, error) {
	return nil, errNotImplemented("GetAbuseQueue")
}

func (Unimplemented) GetApprovalQueue(ctx context.Context, request gen.GetApprovalQueueRequestObject) (gen.GetApprovalQueueResponseObject, error) {
	return nil, errNotImplemented("GetApprovalQueue")
}

func (Unimplemented) GetAuditLog(ctx context.Context, request gen.GetAuditLogRequestObject) (gen.GetAuditLogResponseObject, error) {
	return nil, errNotImplemented("GetAuditLog")
}

func (Unimplemented) OperatorLogin(ctx context.Context, request gen.OperatorLoginRequestObject) (gen.OperatorLoginResponseObject, error) {
	return nil, errNotImplemented("OperatorLogin")
}

func (Unimplemented) GetOperatorMargin(ctx context.Context, request gen.GetOperatorMarginRequestObject) (gen.GetOperatorMarginResponseObject, error) {
	return nil, errNotImplemented("GetOperatorMargin")
}

func (Unimplemented) GetOperatorMe(ctx context.Context, request gen.GetOperatorMeRequestObject) (gen.GetOperatorMeResponseObject, error) {
	return nil, errNotImplemented("GetOperatorMe")
}

func (Unimplemented) GetRateCard(ctx context.Context, request gen.GetRateCardRequestObject) (gen.GetRateCardResponseObject, error) {
	return nil, errNotImplemented("GetRateCard")
}

func (Unimplemented) UpdateDefaultRate(ctx context.Context, request gen.UpdateDefaultRateRequestObject) (gen.UpdateDefaultRateResponseObject, error) {
	return nil, errNotImplemented("UpdateDefaultRate")
}

func (Unimplemented) CreateRateOverride(ctx context.Context, request gen.CreateRateOverrideRequestObject) (gen.CreateRateOverrideResponseObject, error) {
	return nil, errNotImplemented("CreateRateOverride")
}

func (Unimplemented) RemoveRateOverride(ctx context.Context, request gen.RemoveRateOverrideRequestObject) (gen.RemoveRateOverrideResponseObject, error) {
	return nil, errNotImplemented("RemoveRateOverride")
}

func (Unimplemented) EditRateOverride(ctx context.Context, request gen.EditRateOverrideRequestObject) (gen.EditRateOverrideResponseObject, error) {
	return nil, errNotImplemented("EditRateOverride")
}

func (Unimplemented) GetRoutes(ctx context.Context, request gen.GetRoutesRequestObject) (gen.GetRoutesResponseObject, error) {
	return nil, errNotImplemented("GetRoutes")
}

func (Unimplemented) DisableRoute(ctx context.Context, request gen.DisableRouteRequestObject) (gen.DisableRouteResponseObject, error) {
	return nil, errNotImplemented("DisableRoute")
}

func (Unimplemented) EnableRoute(ctx context.Context, request gen.EnableRouteRequestObject) (gen.EnableRouteResponseObject, error) {
	return nil, errNotImplemented("EnableRoute")
}

func (Unimplemented) MoveRouteDown(ctx context.Context, request gen.MoveRouteDownRequestObject) (gen.MoveRouteDownResponseObject, error) {
	return nil, errNotImplemented("MoveRouteDown")
}

func (Unimplemented) MoveRouteUp(ctx context.Context, request gen.MoveRouteUpRequestObject) (gen.MoveRouteUpResponseObject, error) {
	return nil, errNotImplemented("MoveRouteUp")
}

func (Unimplemented) ApproveSenderItem(ctx context.Context, request gen.ApproveSenderItemRequestObject) (gen.ApproveSenderItemResponseObject, error) {
	return nil, errNotImplemented("ApproveSenderItem")
}

func (Unimplemented) RejectSenderItem(ctx context.Context, request gen.RejectSenderItemRequestObject) (gen.RejectSenderItemResponseObject, error) {
	return nil, errNotImplemented("RejectSenderItem")
}

func (Unimplemented) GetOperatorSupportTickets(ctx context.Context, request gen.GetOperatorSupportTicketsRequestObject) (gen.GetOperatorSupportTicketsResponseObject, error) {
	return nil, errNotImplemented("GetOperatorSupportTickets")
}

func (Unimplemented) GetOperatorSupportTicket(ctx context.Context, request gen.GetOperatorSupportTicketRequestObject) (gen.GetOperatorSupportTicketResponseObject, error) {
	return nil, errNotImplemented("GetOperatorSupportTicket")
}

func (Unimplemented) AddOperatorSupportMessage(ctx context.Context, request gen.AddOperatorSupportMessageRequestObject) (gen.AddOperatorSupportMessageResponseObject, error) {
	return nil, errNotImplemented("AddOperatorSupportMessage")
}

func (Unimplemented) ReopenSupportTicket(ctx context.Context, request gen.ReopenSupportTicketRequestObject) (gen.ReopenSupportTicketResponseObject, error) {
	return nil, errNotImplemented("ReopenSupportTicket")
}

func (Unimplemented) ResolveSupportTicket(ctx context.Context, request gen.ResolveSupportTicketRequestObject) (gen.ResolveSupportTicketResponseObject, error) {
	return nil, errNotImplemented("ResolveSupportTicket")
}

func (Unimplemented) ApproveTemplateItem(ctx context.Context, request gen.ApproveTemplateItemRequestObject) (gen.ApproveTemplateItemResponseObject, error) {
	return nil, errNotImplemented("ApproveTemplateItem")
}

func (Unimplemented) RejectTemplateItem(ctx context.Context, request gen.RejectTemplateItemRequestObject) (gen.RejectTemplateItemResponseObject, error) {
	return nil, errNotImplemented("RejectTemplateItem")
}

func (Unimplemented) GetTenants(ctx context.Context, request gen.GetTenantsRequestObject) (gen.GetTenantsResponseObject, error) {
	return nil, errNotImplemented("GetTenants")
}

func (Unimplemented) GetTenantDetail(ctx context.Context, request gen.GetTenantDetailRequestObject) (gen.GetTenantDetailResponseObject, error) {
	return nil, errNotImplemented("GetTenantDetail")
}

func (Unimplemented) DismissFlag(ctx context.Context, request gen.DismissFlagRequestObject) (gen.DismissFlagResponseObject, error) {
	return nil, errNotImplemented("DismissFlag")
}

func (Unimplemented) FlagTenantForAbuse(ctx context.Context, request gen.FlagTenantForAbuseRequestObject) (gen.FlagTenantForAbuseResponseObject, error) {
	return nil, errNotImplemented("FlagTenantForAbuse")
}

func (Unimplemented) ReinstateTenant(ctx context.Context, request gen.ReinstateTenantRequestObject) (gen.ReinstateTenantResponseObject, error) {
	return nil, errNotImplemented("ReinstateTenant")
}

func (Unimplemented) SuspendTenant(ctx context.Context, request gen.SuspendTenantRequestObject) (gen.SuspendTenantResponseObject, error) {
	return nil, errNotImplemented("SuspendTenant")
}

func (Unimplemented) ThrottleTenant(ctx context.Context, request gen.ThrottleTenantRequestObject) (gen.ThrottleTenantResponseObject, error) {
	return nil, errNotImplemented("ThrottleTenant")
}

func (Unimplemented) GetOperatorUsage(ctx context.Context, request gen.GetOperatorUsageRequestObject) (gen.GetOperatorUsageResponseObject, error) {
	return nil, errNotImplemented("GetOperatorUsage")
}

func (Unimplemented) GetUserActivity(ctx context.Context, request gen.GetUserActivityRequestObject) (gen.GetUserActivityResponseObject, error) {
	return nil, errNotImplemented("GetUserActivity")
}

func (Unimplemented) ListPricing(ctx context.Context, request gen.ListPricingRequestObject) (gen.ListPricingResponseObject, error) {
	return nil, errNotImplemented("ListPricing")
}

func (Unimplemented) ListRegistrations(ctx context.Context, request gen.ListRegistrationsRequestObject) (gen.ListRegistrationsResponseObject, error) {
	return nil, errNotImplemented("ListRegistrations")
}

func (Unimplemented) CreateRegistration(ctx context.Context, request gen.CreateRegistrationRequestObject) (gen.CreateRegistrationResponseObject, error) {
	return nil, errNotImplemented("CreateRegistration")
}

func (Unimplemented) GetRegistration(ctx context.Context, request gen.GetRegistrationRequestObject) (gen.GetRegistrationResponseObject, error) {
	return nil, errNotImplemented("GetRegistration")
}

func (Unimplemented) ListSenderIds(ctx context.Context, request gen.ListSenderIdsRequestObject) (gen.ListSenderIdsResponseObject, error) {
	return nil, errNotImplemented("ListSenderIds")
}

func (Unimplemented) CreateSenderId(ctx context.Context, request gen.CreateSenderIdRequestObject) (gen.CreateSenderIdResponseObject, error) {
	return nil, errNotImplemented("CreateSenderId")
}

func (Unimplemented) GetSenderId(ctx context.Context, request gen.GetSenderIdRequestObject) (gen.GetSenderIdResponseObject, error) {
	return nil, errNotImplemented("GetSenderId")
}

func (Unimplemented) RequestVoiceCall(ctx context.Context, request gen.RequestVoiceCallRequestObject) (gen.RequestVoiceCallResponseObject, error) {
	return nil, errNotImplemented("RequestVoiceCall")
}

func (Unimplemented) ConfirmVoiceCode(ctx context.Context, request gen.ConfirmVoiceCodeRequestObject) (gen.ConfirmVoiceCodeResponseObject, error) {
	return nil, errNotImplemented("ConfirmVoiceCode")
}

func (Unimplemented) ListSessions(ctx context.Context, request gen.ListSessionsRequestObject) (gen.ListSessionsResponseObject, error) {
	return nil, errNotImplemented("ListSessions")
}

func (Unimplemented) RevokeSession(ctx context.Context, request gen.RevokeSessionRequestObject) (gen.RevokeSessionResponseObject, error) {
	return nil, errNotImplemented("RevokeSession")
}

func (Unimplemented) ListSuppressions(ctx context.Context, request gen.ListSuppressionsRequestObject) (gen.ListSuppressionsResponseObject, error) {
	return nil, errNotImplemented("ListSuppressions")
}

func (Unimplemented) AddSuppressions(ctx context.Context, request gen.AddSuppressionsRequestObject) (gen.AddSuppressionsResponseObject, error) {
	return nil, errNotImplemented("AddSuppressions")
}

func (Unimplemented) RemoveSuppression(ctx context.Context, request gen.RemoveSuppressionRequestObject) (gen.RemoveSuppressionResponseObject, error) {
	return nil, errNotImplemented("RemoveSuppression")
}

func (Unimplemented) GetTeamMembers(ctx context.Context, request gen.GetTeamMembersRequestObject) (gen.GetTeamMembersResponseObject, error) {
	return nil, errNotImplemented("GetTeamMembers")
}

func (Unimplemented) InviteTeamMember(ctx context.Context, request gen.InviteTeamMemberRequestObject) (gen.InviteTeamMemberResponseObject, error) {
	return nil, errNotImplemented("InviteTeamMember")
}

func (Unimplemented) RemoveTeamMember(ctx context.Context, request gen.RemoveTeamMemberRequestObject) (gen.RemoveTeamMemberResponseObject, error) {
	return nil, errNotImplemented("RemoveTeamMember")
}

func (Unimplemented) UpdateTeamMemberRole(ctx context.Context, request gen.UpdateTeamMemberRoleRequestObject) (gen.UpdateTeamMemberRoleResponseObject, error) {
	return nil, errNotImplemented("UpdateTeamMemberRole")
}

func (Unimplemented) ListTemplates(ctx context.Context, request gen.ListTemplatesRequestObject) (gen.ListTemplatesResponseObject, error) {
	return nil, errNotImplemented("ListTemplates")
}

func (Unimplemented) CreateTemplate(ctx context.Context, request gen.CreateTemplateRequestObject) (gen.CreateTemplateResponseObject, error) {
	return nil, errNotImplemented("CreateTemplate")
}

func (Unimplemented) GetTemplate(ctx context.Context, request gen.GetTemplateRequestObject) (gen.GetTemplateResponseObject, error) {
	return nil, errNotImplemented("GetTemplate")
}

func (Unimplemented) UpdateTenant(ctx context.Context, request gen.UpdateTenantRequestObject) (gen.UpdateTenantResponseObject, error) {
	return nil, errNotImplemented("UpdateTenant")
}

func (Unimplemented) ListVerifyServices(ctx context.Context, request gen.ListVerifyServicesRequestObject) (gen.ListVerifyServicesResponseObject, error) {
	return nil, errNotImplemented("ListVerifyServices")
}

func (Unimplemented) CreateVerifyService(ctx context.Context, request gen.CreateVerifyServiceRequestObject) (gen.CreateVerifyServiceResponseObject, error) {
	return nil, errNotImplemented("CreateVerifyService")
}

func (Unimplemented) GetVerifyService(ctx context.Context, request gen.GetVerifyServiceRequestObject) (gen.GetVerifyServiceResponseObject, error) {
	return nil, errNotImplemented("GetVerifyService")
}

func (Unimplemented) UpdateVerifyService(ctx context.Context, request gen.UpdateVerifyServiceRequestObject) (gen.UpdateVerifyServiceResponseObject, error) {
	return nil, errNotImplemented("UpdateVerifyService")
}

func (Unimplemented) GetVerifyAnalytics(ctx context.Context, request gen.GetVerifyAnalyticsRequestObject) (gen.GetVerifyAnalyticsResponseObject, error) {
	return nil, errNotImplemented("GetVerifyAnalytics")
}

func (Unimplemented) ListVerificationAttempts(ctx context.Context, request gen.ListVerificationAttemptsRequestObject) (gen.ListVerificationAttemptsResponseObject, error) {
	return nil, errNotImplemented("ListVerificationAttempts")
}

func (Unimplemented) CreateVerification(ctx context.Context, request gen.CreateVerificationRequestObject) (gen.CreateVerificationResponseObject, error) {
	return nil, errNotImplemented("CreateVerification")
}

func (Unimplemented) CheckVerification(ctx context.Context, request gen.CheckVerificationRequestObject) (gen.CheckVerificationResponseObject, error) {
	return nil, errNotImplemented("CheckVerification")
}

func (Unimplemented) ListAutoRecharge(ctx context.Context, request gen.ListAutoRechargeRequestObject) (gen.ListAutoRechargeResponseObject, error) {
	return nil, errNotImplemented("ListAutoRecharge")
}

func (Unimplemented) UpdateAutoRecharge(ctx context.Context, request gen.UpdateAutoRechargeRequestObject) (gen.UpdateAutoRechargeResponseObject, error) {
	return nil, errNotImplemented("UpdateAutoRecharge")
}

func (Unimplemented) ListWalletBalances(ctx context.Context, request gen.ListWalletBalancesRequestObject) (gen.ListWalletBalancesResponseObject, error) {
	return nil, errNotImplemented("ListWalletBalances")
}

func (Unimplemented) ListLedger(ctx context.Context, request gen.ListLedgerRequestObject) (gen.ListLedgerResponseObject, error) {
	return nil, errNotImplemented("ListLedger")
}

func (Unimplemented) ListPaymentMethods(ctx context.Context, request gen.ListPaymentMethodsRequestObject) (gen.ListPaymentMethodsResponseObject, error) {
	return nil, errNotImplemented("ListPaymentMethods")
}

func (Unimplemented) AddPaymentMethod(ctx context.Context, request gen.AddPaymentMethodRequestObject) (gen.AddPaymentMethodResponseObject, error) {
	return nil, errNotImplemented("AddPaymentMethod")
}

func (Unimplemented) RemovePaymentMethod(ctx context.Context, request gen.RemovePaymentMethodRequestObject) (gen.RemovePaymentMethodResponseObject, error) {
	return nil, errNotImplemented("RemovePaymentMethod")
}

func (Unimplemented) SetDefaultPaymentMethod(ctx context.Context, request gen.SetDefaultPaymentMethodRequestObject) (gen.SetDefaultPaymentMethodResponseObject, error) {
	return nil, errNotImplemented("SetDefaultPaymentMethod")
}

func (Unimplemented) TopUpWallet(ctx context.Context, request gen.TopUpWalletRequestObject) (gen.TopUpWalletResponseObject, error) {
	return nil, errNotImplemented("TopUpWallet")
}
