// Command gen-unimplemented writes internal/api/unimplemented.go: a struct
// implementing every method of the generated StrictServerInterface with a 501
// response.
//
// It exists because oapi-codegen emits one interface covering all 151
// contract operations, so nothing compiles until all 151 exist. Real handlers
// embed Unimplemented and define only the operations their stage owns, which
// shadow the embedded stubs. That keeps the project building while the
// contract is implemented incrementally, without giving up the property we
// chose oapi-codegen for: if the spec changes the shape of an operation we
// *have* implemented, the build breaks.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

const (
	generatedFile = "internal/gen/api/control.gen.go"
	targetFile    = "internal/api/unimplemented.go"
	interfaceName = "StrictServerInterface"
)

func main() {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, generatedFile, nil, parser.SkipObjectResolution)
	if err != nil {
		fatal(err)
	}

	iface := findInterface(file, interfaceName)
	if iface == nil {
		fatal(fmt.Errorf("%s not found in %s", interfaceName, generatedFile))
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by cmd/gen-unimplemented. DO NOT EDIT.\n\n")
	out.WriteString("package api\n\n")
	out.WriteString("import (\n\t\"context\"\n\n")
	out.WriteString("\tgen \"github.com/saeedafri/sms-be/internal/gen/api\"\n)\n\n")
	out.WriteString("// Unimplemented answers 501 for every contract operation.\n")
	out.WriteString("// Server embeds it; each stage shadows the operations it implements.\n")
	out.WriteString("type Unimplemented struct{}\n\n")

	count := 0
	for _, method := range iface.Methods.List {
		if len(method.Names) == 0 {
			continue
		}
		fn, ok := method.Type.(*ast.FuncType)
		if !ok {
			continue
		}
		name := method.Names[0].Name
		fmt.Fprintf(&out, "func (Unimplemented) %s%s %s {\n\treturn nil, errNotImplemented(%q)\n}\n\n",
			name, qualify(fn.Params), qualify(fn.Results), name)
		count++
	}

	source, err := format.Source(out.Bytes())
	if err != nil {
		fatal(fmt.Errorf("formatting generated source: %w", err))
	}
	if err := os.WriteFile(targetFile, source, 0o644); err != nil {
		fatal(err)
	}
	fmt.Printf("wrote %s (%d operations)\n", targetFile, count)
}

func findInterface(file *ast.File, name string) *ast.InterfaceType {
	var found *ast.InterfaceType
	ast.Inspect(file, func(n ast.Node) bool {
		spec, ok := n.(*ast.TypeSpec)
		if !ok || spec.Name.Name != name {
			return true
		}
		if iface, ok := spec.Type.(*ast.InterfaceType); ok {
			found = iface
		}
		return false
	})
	return found
}

// qualify renders a parameter or result list as parenthesised Go source,
// prefixing the generated package's own types with the gen alias. Inside the
// generated file those types are unqualified; from our package they need the
// import path.
//
// This renders to a string directly rather than going through go/printer.
// The printer positions its output from the original file's token offsets, and
// the rewritten type nodes here have no position, which makes it emit nothing
// at all — silently producing zero-argument methods.
func qualify(list *ast.FieldList) string {
	if list == nil || len(list.List) == 0 {
		return "()"
	}
	fields := make([]string, 0, len(list.List))
	for _, field := range list.List {
		typ := qualifyType(field.Type)
		if len(field.Names) == 0 {
			fields = append(fields, typ)
			continue
		}
		names := make([]string, 0, len(field.Names))
		for _, name := range field.Names {
			names = append(names, name.Name)
		}
		fields = append(fields, strings.Join(names, ", ")+" "+typ)
	}
	return "(" + strings.Join(fields, ", ") + ")"
}

// qualifyType renders a type expression, prefixing names declared in the
// generated package with its alias. Builtins and already-qualified selectors
// (context.Context) pass through untouched.
func qualifyType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		if isBuiltin(t.Name) {
			return t.Name
		}
		return "gen." + t.Name
	case *ast.SelectorExpr:
		// Already package-qualified, e.g. context.Context. The left side is an
		// import name, not a type, so it must not get the gen. prefix.
		pkg, ok := t.X.(*ast.Ident)
		if !ok {
			fatal(fmt.Errorf("unsupported qualifier %T in selector", t.X))
		}
		return pkg.Name + "." + t.Sel.Name
	case *ast.StarExpr:
		return "*" + qualifyType(t.X)
	case *ast.ArrayType:
		return "[]" + qualifyType(t.Elt)
	case *ast.Ellipsis:
		return "..." + qualifyType(t.Elt)
	case *ast.MapType:
		return "map[" + qualifyType(t.Key) + "]" + qualifyType(t.Value)
	case *ast.InterfaceType:
		return "any"
	default:
		fatal(fmt.Errorf("unsupported type expression %T in interface signature", expr))
		return ""
	}
}

func isBuiltin(name string) bool {
	switch name {
	case "error", "string", "bool", "byte", "rune", "any",
		"int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64":
		return true
	}
	return false
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gen-unimplemented:", err)
	os.Exit(1)
}
